export const INSPECTO_API_PATHS = {
  HEALTH: '/inspecto/api/v1/health',
  CLIENT_CONFIG: '/inspecto/api/v1/client/config',
  IDE_INFO: '/inspecto/api/v1/ide/info',
  IDE_OPEN: '/inspecto/api/v1/ide/open',
  SOURCE_OPEN: '/inspecto/api/v1/source/open',
  PROJECT_SNIPPET: '/inspecto/api/v1/project/snippet',
  AI_DISPATCH: '/inspecto/api/v1/ai/dispatch',
  AI_BATCH_DISPATCH: '/inspecto/api/v1/ai/dispatch/annotations',
  AI_TICKET: '/inspecto/api/v1/ai/ticket',
  SESSIONS: '/inspecto/api/v1/sessions',
  SESSION_CLAIM_NEXT: '/inspecto/api/v1/sessions/claim',
  SESSION_EVENTS: '/inspecto/api/v1/sessions/events',
  SESSION_REPLY_SUFFIX: '/reply',
  SESSION_RESOLVE_SUFFIX: '/resolve',
  SESSION_DISMISS_SUFFIX: '/dismiss',
} as const
